#!/usr/bin/env python3
"""
Berlin Secondary School Data Asset Builder Orchestrator
========================================================

This orchestrator script executes the complete data pipeline to build the
comprehensive Berlin secondary school master data table. It coordinates
multiple data scraping, enrichment, and processing stages in the correct
order with proper dependency management.

PIPELINE OVERVIEW
-----------------
The pipeline consists of 8 major phases:

    Phase 1: Initial Data Scraping
        - Scrape ISS (Integrierte Sekundarschule) data from sekundarschulen-berlin.de
        - Scrape Gymnasium data from bildung.berlin.de
        - Scrape ISS data from bildung.berlin.de

    Phase 2: Data Combination & Deduplication
        - Merge all scraped data sources
        - Handle schools offering both ISS and Gymnasium tracks
        - Normalize and deduplicate records

    Phase 3: MSA Statistics Enrichment
        - Add district-level MSA (Mittlerer Schulabschluss) statistics
        - Provides performance context for schools without Abitur data

    Phase 4: Metadata Enrichment
        - Fill missing metadata using scraped website data
        - Add founding years, special programs, etc.

    Phase 5: Geospatial & Context Enrichment
        - Add traffic data from Berlin sensors
        - Add crime statistics by district
        - Add public transit accessibility scores
        - Add nearby points of interest (POIs)

    Phase 6: School Descriptions Generation
        - Crawl school websites for detailed information
        - Extract tuition data for private schools
        - Generate rich descriptions using LLM

    Phase 7: Vision-Based Data Validation
        - Use GPT-5-mini vision to scrape missing data from bildung.berlin.de
        - Take screenshots and let LLM interpret tables for accuracy
        - Fill in student counts, teacher counts, migration percentages

    Phase 8: Embeddings & Similarity Computation
        - Generate text embeddings using OpenAI text-embedding-3-large
        - Compute cosine similarity between all schools
        - Identify top 3 most similar schools for each school


OUTPUT FILES
------------
The pipeline produces:
    - school_master_table_final_with_embeddings.parquet
        The complete master data table with all enrichments, descriptions,
        embeddings, and similarity scores.

    - school_descriptions_v4/
        Individual JSON files with detailed school information

    - screenshots/
        Screenshots from vision-based scraping (for debugging)


USAGE
-----
    # Run complete pipeline
    python3 Berlin_secondary_school_data_asset_builder_orchestrator.py

    # Run specific phases only
    python3 Berlin_secondary_school_data_asset_builder_orchestrator.py --phases 1,2,3

    # Skip certain phases
    python3 Berlin_secondary_school_data_asset_builder_orchestrator.py --skip-phases 6

    # Dry run (show what would be executed)
    python3 Berlin_secondary_school_data_asset_builder_orchestrator.py --dry-run

    # Resume from a specific phase
    python3 Berlin_secondary_school_data_asset_builder_orchestrator.py --start-from 5


REQUIREMENTS
------------
    - Python 3.9+
    - See requirements_crawler.txt for dependencies
    - API keys configured in config.yaml:
        - OpenAI API key (for embeddings and vision)
        - Gemini API key (optional, for descriptions)
        - Perplexity API key (optional, for descriptions)
    - Chrome/Chromium installed (for Selenium-based scraping)


CONFIGURATION
-------------
The pipeline reads configuration from config.yaml:
    - api_keys: API keys for various services
    - models: Model names for LLM operations
    - rate_limits: Delays between API calls


AUTHOR
------
Generated by Claude Code for the SchoolNossa project.
Berlin Secondary School Data Pipeline v1.0
"""

import os
import sys
import time
import argparse
import subprocess
import logging
from pathlib import Path
from datetime import datetime
from typing import List, Optional, Dict, Tuple, Callable
from dataclasses import dataclass, field
from enum import Enum

# Rich library for beautiful progress bars and console output
try:
    from rich.console import Console
    from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TaskProgressColumn, TimeElapsedColumn, TimeRemainingColumn
    from rich.panel import Panel
    from rich.table import Table
    from rich.live import Live
    from rich.layout import Layout
    from rich import print as rprint
    RICH_AVAILABLE = True
except ImportError:
    RICH_AVAILABLE = False
    print("Warning: 'rich' library not installed. Install with: pip install rich")
    print("Falling back to basic output.")

# Configure logging
LOG_FILE = Path(__file__).parent / "orchestrator.log"
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


class PhaseStatus(Enum):
    """Status of a pipeline phase."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass
class PipelinePhase:
    """
    Represents a single phase in the data pipeline.

    Attributes:
        id: Unique phase identifier (1-8)
        name: Human-readable phase name
        description: Detailed description of what this phase does
        scripts: List of scripts to execute in this phase
        input_files: Files that must exist before this phase runs
        output_files: Files produced by this phase
        estimated_duration: Estimated time to complete (minutes)
        status: Current status of the phase
        can_parallelize: Whether scripts in this phase can run in parallel
    """
    id: int
    name: str
    description: str
    scripts: List[Dict[str, str]]  # [{"script": "name.py", "args": "--flag"}]
    input_files: List[str] = field(default_factory=list)
    output_files: List[str] = field(default_factory=list)
    estimated_duration: int = 10  # minutes
    status: PhaseStatus = PhaseStatus.PENDING
    can_parallelize: bool = False
    custom_function: Optional[Callable] = None  # For phases that need custom logic


def define_pipeline_phases() -> List[PipelinePhase]:
    """
    Define all phases of the data pipeline with their dependencies.

    Returns:
        List of PipelinePhase objects in execution order.

    Note:
        Scripts are organized in subdirectories:
        - scrapers/: Data collection from web sources
        - enrichment/: Adding contextual data
        - processing/: Data combination and transformation
        - ../scripts_shared/: Reusable scripts across cities
    """
    phases = [
        # Phase 1: Initial Data Scraping
        PipelinePhase(
            id=1,
            name="Initial Data Scraping",
            description="Scrape school data from sekundarschulen-berlin.de and bildung.berlin.de",
            scripts=[
                {"script": "scrapers/ISS_data_scraper.py", "args": ""},
                {"script": "scrapers/bildung_berlin_gymnasien_scraper.py", "args": ""},
                {"script": "scrapers/bildung_berlin_iss_scraper.py", "args": ""},
            ],
            input_files=[],
            output_files=[
                "data_berlin/raw/ISS_master_table.csv",
                "data_berlin/raw/bildung_berlin_gymnasien.csv",
                "data_berlin/raw/bildung_berlin_iss.csv",
            ],
            estimated_duration=15,
            can_parallelize=True,
        ),

        # Phase 2: Data Combination
        PipelinePhase(
            id=2,
            name="Data Combination & Deduplication",
            description="Merge all data sources, handle dual ISS-Gymnasium schools, normalize records",
            scripts=[
                {"script": "processing/combine_gymnasium_iss_bildung_berlin_and_metadata.py", "args": ""},
            ],
            input_files=[
                "data_berlin/raw/ISS_master_table.csv",
                "data_berlin/raw/bildung_berlin_gymnasien.csv",
                "data_berlin/raw/bildung_berlin_iss.csv",
            ],
            output_files=[
                "data_berlin/intermediate/combined_schools_with_metadata.csv",
            ],
            estimated_duration=2,
        ),

        # Phase 3: MSA Statistics Enrichment
        PipelinePhase(
            id=3,
            name="MSA Statistics Enrichment",
            description="Add district-level MSA (Mittlerer Schulabschluss) performance statistics",
            scripts=[
                {"script": "enrichment/add_msa_to_combined_master.py", "args": ""},
            ],
            input_files=[
                "data_berlin/intermediate/combined_schools_with_metadata.csv",
            ],
            output_files=[
                "data_berlin/intermediate/combined_schools_with_metadata_msa.csv",
            ],
            estimated_duration=2,
        ),

        # Phase 4: Metadata Enrichment
        PipelinePhase(
            id=4,
            name="Metadata Enrichment",
            description="Fill missing metadata from school websites and official sources",
            scripts=[
                {"script": "processing/merge_scraped_metadata.py", "args": ""},
            ],
            input_files=[
                "data_berlin/intermediate/combined_schools_with_metadata_msa.csv",
                "data_berlin/intermediate/scraped_missing_metadata.csv",
            ],
            output_files=[
                "data_berlin/intermediate/combined_schools_with_metadata_msa.csv",  # Updated in place
            ],
            estimated_duration=2,
        ),

        # Phase 5: Geospatial & Context Enrichment
        PipelinePhase(
            id=5,
            name="Geospatial & Context Enrichment",
            description="Add traffic data, crime statistics, transit scores, and POIs",
            scripts=[
                {"script": "enrichment/enrich_schools_with_traffic.py", "args": ""},
                {"script": "../scripts_shared/enrichment/enrich_berlin_schools_with_crime.py",
                 "args": "--input data_berlin/intermediate/combined_schools_with_metadata_msa.csv"},
                {"script": "enrichment/enrich_schools_with_transit.py", "args": ""},
                {"script": "../scripts_shared/enrichment/enrich_schools_with_pois.py", "args": ""},
            ],
            input_files=[
                "data_berlin/intermediate/combined_schools_with_metadata_msa.csv",
                "data_berlin/raw/bezirk_crime_statistics.csv",
            ],
            output_files=[
                "data_berlin/final/school_master_table_final.csv",
            ],
            estimated_duration=30,
            can_parallelize=False,  # These modify the same file sequentially
        ),

        # Phase 6: School Descriptions Generation
        PipelinePhase(
            id=6,
            name="School Descriptions Generation",
            description="Crawl school websites and generate rich descriptions using LLM",
            scripts=[
                {"script": "../scripts_shared/generation/generate_school_descriptions_v4.py", "args": "--input data_berlin/final/school_master_table_final.csv"},
            ],
            input_files=[
                "data_berlin/final/school_master_table_final.csv",
            ],
            output_files=[
                "data_berlin/descriptions/school_descriptions_v4/descriptions_summary.csv",
                "data_berlin/intermediate/combined_schools_with_metadata_msa_with_descriptions_v2_v3_v4.csv",
            ],
            estimated_duration=180,  # This is the longest phase
        ),

        # Phase 7: Vision-Based Data Validation
        PipelinePhase(
            id=7,
            name="Vision-Based Data Scraping",
            description="Use GPT vision to scrape missing data from bildung.berlin.de screenshots",
            scripts=[
                {"script": "scrapers/scrape_bildung_berlin_v2.py", "args": "--missing-only"},
            ],
            input_files=[
                "data_berlin/final/school_master_table_final.csv",
            ],
            output_files=[
                "data_berlin/intermediate/school_master_table_vision_enriched.csv",
            ],
            estimated_duration=150,  # ~1 min per school, ~150 schools
        ),

        # Phase 8: Embeddings & Similarity
        PipelinePhase(
            id=8,
            name="Embeddings & Similarity Computation",
            description="Generate OpenAI embeddings and compute school similarity scores",
            scripts=[],  # Custom function handles this
            input_files=[
                "data_berlin/intermediate/school_master_table_vision_enriched.csv",
            ],
            output_files=[
                "data_berlin/final/school_master_table_final_with_embeddings.parquet",
            ],
            estimated_duration=10,
            custom_function=None,  # Will be set below
        ),
    ]

    return phases


class PipelineOrchestrator:
    """
    Orchestrates the execution of the Berlin school data pipeline.

    This class manages the sequential execution of pipeline phases,
    handles dependencies, provides progress tracking, and manages
    error recovery.

    Attributes:
        base_dir: Base directory containing all scripts and data
        phases: List of pipeline phases to execute
        console: Rich console for output (if available)
        dry_run: If True, only show what would be executed
    """

    def __init__(self, base_dir: Optional[Path] = None, dry_run: bool = False):
        """
        Initialize the pipeline orchestrator.

        Args:
            base_dir: Base directory for scripts and data. Defaults to project root.
            dry_run: If True, don't actually execute anything.
        """
        # Base dir is project root (parent of scripts_berlin)
        self.base_dir = base_dir or Path(__file__).parent.parent
        self.scripts_dir = self.base_dir / "scripts_berlin"
        self.dry_run = dry_run
        self.phases = define_pipeline_phases()
        self.start_time = None
        self.console = Console() if RICH_AVAILABLE else None

        # Set custom function for Phase 8
        for phase in self.phases:
            if phase.id == 8:
                phase.custom_function = self._run_embeddings_phase

    def _print(self, message: str, style: str = None):
        """Print message using Rich if available, otherwise plain print."""
        if self.console and RICH_AVAILABLE:
            self.console.print(message, style=style)
        else:
            print(message)

    def _check_file_exists(self, filename: str) -> bool:
        """Check if a file exists in the base directory."""
        filepath = self.base_dir / filename
        return filepath.exists()

    def _check_dependencies(self, phase: PipelinePhase) -> Tuple[bool, List[str]]:
        """
        Check if all input dependencies for a phase exist.

        Args:
            phase: The phase to check dependencies for.

        Returns:
            Tuple of (all_satisfied, list_of_missing_files)
        """
        missing = []
        for input_file in phase.input_files:
            if not self._check_file_exists(input_file):
                missing.append(input_file)

        return len(missing) == 0, missing

    def _run_script(self, script_info: Dict[str, str], phase_name: str) -> Tuple[bool, str]:
        """
        Execute a single Python script.

        Args:
            script_info: Dictionary with 'script' and 'args' keys
            phase_name: Name of the current phase (for logging)

        Returns:
            Tuple of (success, output_or_error_message)
        """
        script = script_info["script"]
        args = script_info.get("args", "")

        # Handle relative paths - scripts starting with ../ are relative to scripts_berlin
        if script.startswith("../"):
            script_path = self.scripts_dir / script
        else:
            script_path = self.scripts_dir / script

        script_path = script_path.resolve()
        if not script_path.exists():
            return False, f"Script not found: {script_path}"

        cmd = f"python3 {script_path}"
        if args:
            cmd += f" {args}"

        logger.info(f"[{phase_name}] Running: {cmd}")

        if self.dry_run:
            return True, f"[DRY RUN] Would execute: {cmd}"

        try:
            # Run the script and capture output in real-time
            process = subprocess.Popen(
                cmd,
                shell=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                cwd=self.base_dir,
            )

            output_lines = []
            while True:
                line = process.stdout.readline()
                if not line and process.poll() is not None:
                    break
                if line:
                    line = line.rstrip()
                    output_lines.append(line)
                    # Show progress lines
                    if any(kw in line.lower() for kw in ['processing', 'progress', 'completed', '%', 'updated']):
                        logger.info(f"  {line}")

            return_code = process.wait()
            output = "\n".join(output_lines)

            if return_code == 0:
                return True, output
            else:
                return False, f"Script failed with code {return_code}:\n{output}"

        except Exception as e:
            return False, f"Error running script: {str(e)}"

    def _run_embeddings_phase(self) -> Tuple[bool, str]:
        """
        Custom function for Phase 8: Generate embeddings and compute similarity.

        This phase:
        1. Loads the vision-enriched CSV
        2. Generates metadata descriptions for schools missing them
        3. Generates embeddings using OpenAI text-embedding-3-large
        4. Computes cosine similarity between all schools
        5. Adds top 3 most similar schools for each school
        6. Saves to parquet format

        Returns:
            Tuple of (success, message)
        """
        if self.dry_run:
            return True, "[DRY RUN] Would generate embeddings and compute similarity"

        try:
            import yaml
            import numpy as np
            import pandas as pd
            import requests
            from sklearn.metrics.pairwise import cosine_similarity

            # Load config
            config_path = self.base_dir / "config.yaml"
            with open(config_path, 'r') as f:
                config = yaml.safe_load(f)

            api_key = config.get('api_keys', {}).get('openai')
            if not api_key:
                return False, "OpenAI API key not found in config.yaml"

            # Load data
            logger.info("Loading data...")
            input_file = self.base_dir / "data_berlin/intermediate/school_master_table_vision_enriched.csv"
            if not input_file.exists():
                input_file = self.base_dir / "data_berlin/final/school_master_table_final.csv"

            df = pd.read_csv(input_file)
            logger.info(f"  Loaded {len(df)} schools")

            # Generate descriptions for schools missing them
            def generate_description_from_metadata(row):
                parts = []
                name = row.get('schulname', '')
                school_type = row.get('school_type', '')
                schulart = row.get('schulart', '')
                traegerschaft = row.get('traegerschaft', '')

                if name:
                    type_str = schulart if pd.notna(schulart) else school_type
                    ownership = f" ({traegerschaft})" if pd.notna(traegerschaft) else ""
                    parts.append(f"{name} is a {type_str}{ownership} in Berlin.")

                bezirk = row.get('bezirk', '')
                ortsteil = row.get('ortsteil', '')
                plz = row.get('plz', '')

                location_parts = []
                if pd.notna(ortsteil) and ortsteil:
                    location_parts.append(str(ortsteil))
                if pd.notna(bezirk) and bezirk:
                    location_parts.append(f"district of {bezirk}")
                if pd.notna(plz) and plz:
                    location_parts.append(f"postal code {int(plz) if isinstance(plz, float) else plz}")

                if location_parts:
                    parts.append(f"Located in {', '.join(location_parts)}.")

                schueler = row.get('schueler_2024_25')
                lehrer = row.get('lehrer_2024_25')

                if pd.notna(schueler) and schueler > 0:
                    student_str = f"The school has approximately {int(schueler)} students"
                    if pd.notna(lehrer) and lehrer > 0:
                        ratio = schueler / lehrer
                        student_str += f" and {int(lehrer)} teachers (student-teacher ratio: {ratio:.1f}:1)"
                    student_str += "."
                    parts.append(student_str)

                sprachen = row.get('sprachen', '')
                if pd.notna(sprachen) and sprachen:
                    parts.append(f"Languages offered: {sprachen}.")

                migration = row.get('migration_2024_25')
                if pd.notna(migration):
                    parts.append(f"Students with non-German native language: {migration:.1f}%.")

                return " ".join(parts)

            # Fill missing descriptions
            missing_mask = df['description'].isna() | (df['description'].apply(lambda x: len(str(x)) if pd.notna(x) else 0) < 100)
            missing_count = missing_mask.sum()

            if missing_count > 0:
                logger.info(f"  Generating descriptions for {missing_count} schools...")
                for idx in df[missing_mask].index:
                    df.at[idx, 'description'] = generate_description_from_metadata(df.loc[idx])

            # Generate embeddings
            logger.info("Generating embeddings with text-embedding-3-large...")

            MODEL = "text-embedding-3-large"
            BASE_URL = "https://api.openai.com/v1/embeddings"

            headers = {
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json"
            }

            descriptions = df['description'].tolist()
            all_embeddings = []
            batch_size = 10

            for i in range(0, len(descriptions), batch_size):
                batch = descriptions[i:i + batch_size]
                batch = [str(t)[:15000] if t else "No description" for t in batch]

                data = {"model": MODEL, "input": batch}
                response = requests.post(BASE_URL, headers=headers, json=data, timeout=120)
                response.raise_for_status()

                result = response.json()
                batch_embeddings = [item["embedding"] for item in result["data"]]
                all_embeddings.extend(batch_embeddings)

                logger.info(f"  Embeddings: {i + len(batch)}/{len(descriptions)}")
                time.sleep(0.3)

            embeddings_array = np.array(all_embeddings)
            logger.info(f"  Embedding shape: {embeddings_array.shape}")

            # Add embeddings to dataframe
            df['embedding'] = list(embeddings_array)

            # Compute similarity
            logger.info("Computing cosine similarity...")
            similarity_matrix = cosine_similarity(embeddings_array)

            # Find top 3 most similar for each school
            logger.info("Finding top 3 most similar schools...")
            schulnummers = df['schulnummer'].tolist()

            most_similar_01 = []
            most_similar_02 = []
            most_similar_03 = []

            for i in range(len(df)):
                similarities = similarity_matrix[i].copy()
                similarities[i] = -1
                top_indices = np.argsort(similarities)[::-1][:3]

                most_similar_01.append(schulnummers[top_indices[0]])
                most_similar_02.append(schulnummers[top_indices[1]])
                most_similar_03.append(schulnummers[top_indices[2]])

            df['most_similar_school_no_01'] = most_similar_01
            df['most_similar_school_no_02'] = most_similar_02
            df['most_similar_school_no_03'] = most_similar_03

            # Save to parquet
            output_path = self.base_dir / "data_berlin/final/school_master_table_final_with_embeddings.parquet"
            logger.info(f"Saving to {output_path}...")
            df.to_parquet(output_path, index=False)

            return True, f"Successfully generated embeddings and saved to {output_path}"

        except Exception as e:
            import traceback
            return False, f"Error in embeddings phase: {str(e)}\n{traceback.format_exc()}"

    def run_phase(self, phase: PipelinePhase) -> bool:
        """
        Execute a single pipeline phase.

        Args:
            phase: The phase to execute.

        Returns:
            True if phase completed successfully, False otherwise.
        """
        phase.status = PhaseStatus.RUNNING

        self._print(f"\n{'='*60}", style="bold blue")
        self._print(f"Phase {phase.id}: {phase.name}", style="bold blue")
        self._print(f"{'='*60}", style="bold blue")
        self._print(f"\n{phase.description}\n")

        # Check dependencies
        deps_satisfied, missing = self._check_dependencies(phase)
        if not deps_satisfied:
            self._print(f"Missing dependencies: {missing}", style="bold red")
            self._print("Attempting to continue anyway...", style="yellow")

        # Run custom function if defined
        if phase.custom_function:
            self._print("Running custom phase logic...", style="cyan")
            success, message = phase.custom_function()
            if success:
                phase.status = PhaseStatus.COMPLETED
                self._print(f"Phase {phase.id} completed successfully!", style="bold green")
            else:
                phase.status = PhaseStatus.FAILED
                self._print(f"Phase {phase.id} failed: {message}", style="bold red")
            return success

        # Run scripts
        for script_info in phase.scripts:
            script_name = script_info["script"]
            self._print(f"\nRunning: {script_name}", style="cyan")

            success, output = self._run_script(script_info, phase.name)

            if not success:
                phase.status = PhaseStatus.FAILED
                self._print(f"Failed: {output}", style="bold red")
                return False

            self._print(f"Completed: {script_name}", style="green")

        # Verify outputs
        for output_file in phase.output_files:
            if not self._check_file_exists(output_file):
                self._print(f"Warning: Expected output not found: {output_file}", style="yellow")

        phase.status = PhaseStatus.COMPLETED
        self._print(f"\nPhase {phase.id} completed successfully!", style="bold green")
        return True

    def run_pipeline(
        self,
        phases_to_run: Optional[List[int]] = None,
        skip_phases: Optional[List[int]] = None,
        start_from: Optional[int] = None,
    ) -> bool:
        """
        Execute the complete pipeline or specified phases.

        Args:
            phases_to_run: Specific phase IDs to run. If None, runs all.
            skip_phases: Phase IDs to skip.
            start_from: Start from this phase ID (skip earlier phases).

        Returns:
            True if all phases completed successfully.
        """
        self.start_time = datetime.now()

        # Determine which phases to run
        phases = self.phases.copy()

        if phases_to_run:
            phases = [p for p in phases if p.id in phases_to_run]

        if skip_phases:
            phases = [p for p in phases if p.id not in skip_phases]

        if start_from:
            phases = [p for p in phases if p.id >= start_from]

        # Print pipeline summary
        self._print_pipeline_summary(phases)

        # Run phases
        total_phases = len(phases)
        completed_phases = 0

        if RICH_AVAILABLE and self.console:
            with Progress(
                SpinnerColumn(),
                TextColumn("[bold blue]{task.description}"),
                BarColumn(),
                TaskProgressColumn(),
                TimeElapsedColumn(),
                console=self.console,
            ) as progress:
                overall_task = progress.add_task(
                    f"[bold]Pipeline Progress",
                    total=total_phases,
                )

                for phase in phases:
                    progress.update(
                        overall_task,
                        description=f"[bold]Phase {phase.id}: {phase.name}",
                    )

                    success = self.run_phase(phase)

                    if success:
                        completed_phases += 1
                        progress.advance(overall_task)
                    else:
                        self._print(f"\nPipeline stopped at Phase {phase.id}", style="bold red")
                        break
        else:
            for i, phase in enumerate(phases):
                print(f"\n[Pipeline Progress: {i+1}/{total_phases}]")

                success = self.run_phase(phase)

                if success:
                    completed_phases += 1
                else:
                    print(f"\nPipeline stopped at Phase {phase.id}")
                    break

        # Print summary
        self._print_final_summary(completed_phases, total_phases)

        return completed_phases == total_phases

    def _print_pipeline_summary(self, phases: List[PipelinePhase]):
        """Print a summary of phases to be executed."""
        self._print("\n" + "="*70, style="bold")
        self._print("BERLIN SECONDARY SCHOOL DATA ASSET BUILDER", style="bold cyan")
        self._print("="*70, style="bold")

        if RICH_AVAILABLE:
            table = Table(title="Pipeline Phases")
            table.add_column("Phase", style="cyan")
            table.add_column("Name", style="white")
            table.add_column("Est. Duration", style="yellow")
            table.add_column("Scripts", style="green")

            for phase in phases:
                scripts = ", ".join([s["script"] for s in phase.scripts]) or "Custom"
                table.add_row(
                    str(phase.id),
                    phase.name,
                    f"{phase.estimated_duration} min",
                    scripts[:40] + "..." if len(scripts) > 40 else scripts,
                )

            self.console.print(table)
        else:
            print("\nPhases to execute:")
            for phase in phases:
                print(f"  {phase.id}. {phase.name} (~{phase.estimated_duration} min)")

        total_time = sum(p.estimated_duration for p in phases)
        self._print(f"\nEstimated total duration: {total_time} minutes ({total_time/60:.1f} hours)", style="yellow")
        self._print("")

    def _print_final_summary(self, completed: int, total: int):
        """Print final pipeline summary."""
        elapsed = datetime.now() - self.start_time

        self._print("\n" + "="*70, style="bold")
        self._print("PIPELINE COMPLETE", style="bold green" if completed == total else "bold red")
        self._print("="*70, style="bold")

        self._print(f"\nPhases completed: {completed}/{total}")
        self._print(f"Total time: {elapsed}")

        if completed == total:
            self._print("\nFinal output: school_master_table_final_with_embeddings.parquet", style="bold green")

        # Show phase statuses
        if RICH_AVAILABLE:
            table = Table(title="Phase Status")
            table.add_column("Phase", style="cyan")
            table.add_column("Name", style="white")
            table.add_column("Status", style="white")

            for phase in self.phases:
                status_style = {
                    PhaseStatus.COMPLETED: "green",
                    PhaseStatus.FAILED: "red",
                    PhaseStatus.SKIPPED: "yellow",
                    PhaseStatus.PENDING: "dim",
                    PhaseStatus.RUNNING: "blue",
                }.get(phase.status, "white")

                table.add_row(
                    str(phase.id),
                    phase.name,
                    f"[{status_style}]{phase.status.value}[/{status_style}]",
                )

            self.console.print(table)


def main():
    """Main entry point for the orchestrator."""
    parser = argparse.ArgumentParser(
        description="Berlin Secondary School Data Asset Builder Orchestrator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Run complete pipeline
  python3 Berlin_secondary_school_data_asset_builder_orchestrator.py

  # Run specific phases only
  python3 Berlin_secondary_school_data_asset_builder_orchestrator.py --phases 1,2,3

  # Skip certain phases
  python3 Berlin_secondary_school_data_asset_builder_orchestrator.py --skip-phases 6

  # Resume from phase 5
  python3 Berlin_secondary_school_data_asset_builder_orchestrator.py --start-from 5

  # Dry run (show what would be executed)
  python3 Berlin_secondary_school_data_asset_builder_orchestrator.py --dry-run
        """
    )

    parser.add_argument(
        "--phases",
        type=str,
        help="Comma-separated list of phase IDs to run (e.g., '1,2,3')",
    )
    parser.add_argument(
        "--skip-phases",
        type=str,
        help="Comma-separated list of phase IDs to skip (e.g., '6,7')",
    )
    parser.add_argument(
        "--start-from",
        type=int,
        help="Start from this phase ID (skip earlier phases)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be executed without actually running",
    )
    parser.add_argument(
        "--base-dir",
        type=str,
        help="Base directory for scripts and data",
    )

    args = parser.parse_args()

    # Parse phase lists
    phases_to_run = None
    if args.phases:
        phases_to_run = [int(p.strip()) for p in args.phases.split(",")]

    skip_phases = None
    if args.skip_phases:
        skip_phases = [int(p.strip()) for p in args.skip_phases.split(",")]

    # Create and run orchestrator
    base_dir = Path(args.base_dir) if args.base_dir else None
    orchestrator = PipelineOrchestrator(base_dir=base_dir, dry_run=args.dry_run)

    success = orchestrator.run_pipeline(
        phases_to_run=phases_to_run,
        skip_phases=skip_phases,
        start_from=args.start_from,
    )

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
