#!/usr/bin/env python3
"""
Berlin Primary School (Grundschule) Data Asset Builder Orchestrator
====================================================================

This orchestrator script executes the complete data pipeline to build the
comprehensive Berlin primary school master data table. It coordinates
multiple data scraping, enrichment, and processing stages in the correct
order with proper dependency management.

PIPELINE OVERVIEW
-----------------
The pipeline consists of 10 major phases:

    Phase 1: Initial Data Scraping
        - Scrape Grundschule data from bildung.berlin.de

    Phase 2: Data Combination & Processing
        - Process scraped data
        - Add schema columns for compatibility with secondary school data
        - Add traegerschaft (public/private) classification

    Phase 3: Geospatial Enrichment - Traffic
        - Geocode school addresses
        - Add traffic data from Berlin sensors

    Phase 4: Crime Data Enrichment
        - Add Berlin district crime statistics
        - Derive bezirk from schulnummer
        - Merge crime data from local data asset

    Phase 5: School Statistics Enrichment
        - Add student/teacher counts from bildungsstatistik.berlin.de
        - Download CSV if not already cached
        - Join on schulnummer (BSN)

    Phase 6: Geospatial Enrichment - Transit
        - Add public transit accessibility scores
        - Store nearest U/S-Bahn, Tram, and Bus stops

    Phase 7: Geospatial Enrichment - POIs
        - Add nearby points of interest (POIs)
        - Categories: supermarkets, restaurants, kitas, secondary schools, parks

    Phase 8: School Descriptions Generation
        - Crawl school websites for detailed information
        - Extract tuition data for private schools
        - Generate rich descriptions using LLM

    Phase 9: Website Metadata Extraction
        - Extract sprachen (languages taught) from school websites
        - Extract gruendungsjahr (founding year) where available
        - Extract besonderheiten (special features) from school profiles
        - Uses OpenAI gpt-4o-mini for structured extraction

    Phase 10 (Optional): Embeddings & Similarity Computation
        - Generate text embeddings using OpenAI text-embedding-3-large
        - Compute cosine similarity between all schools
        - Identify top 3 most similar schools for each school


OUTPUT FILES
------------
The pipeline produces:
    - data_berlin_primary/final/grundschule_master_table_final.csv
        The complete master data table with all enrichments

    - data_berlin_primary/final/grundschule_master_table_final_with_embeddings.parquet
        Master table with embeddings and similarity scores


SCHEMA COMPATIBILITY
-------------------
The output schema maintains compatibility with secondary school data:
- Same column names where applicable
- MSA/Abitur columns present but empty (not applicable to primary schools)
- School type = "Grundschule"


USAGE
-----
    # Run complete pipeline
    python3 Berlin_primary_school_data_asset_builder_orchestrator.py

    # Run specific phases only
    python3 Berlin_primary_school_data_asset_builder_orchestrator.py --phases 1,2,3

    # Skip certain phases
    python3 Berlin_primary_school_data_asset_builder_orchestrator.py --skip-phases 6

    # Dry run (show what would be executed)
    python3 Berlin_primary_school_data_asset_builder_orchestrator.py --dry-run

    # Resume from a specific phase
    python3 Berlin_primary_school_data_asset_builder_orchestrator.py --start-from 3


REQUIREMENTS
------------
    - Python 3.9+
    - See requirements_crawler.txt for dependencies
    - API keys configured in config.yaml:
        - OpenAI API key (for embeddings and descriptions)
        - Google Places API key (for POI enrichment)


AUTHOR
------
Generated by Claude Code for the SchoolNossa project.
Berlin Primary School Data Pipeline v1.0
"""

import os
import sys
import time
import argparse
import subprocess
import logging
from pathlib import Path
from datetime import datetime
from typing import List, Optional, Dict, Tuple, Callable
from dataclasses import dataclass, field
from enum import Enum

# Rich library for beautiful progress bars and console output
try:
    from rich.console import Console
    from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn, TaskProgressColumn, TimeElapsedColumn, TimeRemainingColumn
    from rich.panel import Panel
    from rich.table import Table
    from rich.live import Live
    from rich.layout import Layout
    from rich import print as rprint
    RICH_AVAILABLE = True
except ImportError:
    RICH_AVAILABLE = False
    print("Warning: 'rich' library not installed. Install with: pip install rich")
    print("Falling back to basic output.")

# Configure logging
SCRIPT_DIR = Path(__file__).parent
LOG_FILE = SCRIPT_DIR / "orchestrator_primary.log"
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


class PhaseStatus(Enum):
    """Status of a pipeline phase."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass
class PipelinePhase:
    """
    Represents a single phase in the data pipeline.

    Attributes:
        id: Unique phase identifier (1-7)
        name: Human-readable phase name
        description: Detailed description of what this phase does
        scripts: List of scripts to execute in this phase
        input_files: Files that must exist before this phase runs
        output_files: Files produced by this phase
        estimated_duration: Estimated time to complete (minutes)
        status: Current status of the phase
        can_parallelize: Whether scripts in this phase can run in parallel
    """
    id: int
    name: str
    description: str
    scripts: List[Dict[str, str]]  # [{"script": "name.py", "args": "--flag"}]
    input_files: List[str] = field(default_factory=list)
    output_files: List[str] = field(default_factory=list)
    estimated_duration: int = 10  # minutes
    status: PhaseStatus = PhaseStatus.PENDING
    can_parallelize: bool = False
    custom_function: Optional[Callable] = None  # For phases that need custom logic


def define_pipeline_phases() -> List[PipelinePhase]:
    """
    Define all phases of the primary school data pipeline with their dependencies.

    Returns:
        List of PipelinePhase objects in execution order.

    Note:
        Scripts are organized in subdirectories:
        - scrapers/: Data collection from web sources
        - enrichment/: Adding contextual data
        - processing/: Data combination and transformation
        - ../scripts_shared/: Reusable scripts across cities
    """
    phases = [
        # Phase 1: Initial Data Scraping
        PipelinePhase(
            id=1,
            name="Initial Data Scraping",
            description="Scrape Grundschule data from bildung.berlin.de",
            scripts=[
                {"script": "scrapers/bildung_berlin_grundschulen_scraper.py", "args": ""},
            ],
            input_files=[],
            output_files=[
                "data_berlin_primary/raw/bildung_berlin_grundschulen.csv",
            ],
            estimated_duration=20,  # ~400 schools * 0.5s per school
            can_parallelize=False,
        ),

        # Phase 2: Data Combination & Processing
        PipelinePhase(
            id=2,
            name="Data Combination & Processing",
            description="Process scraped data, add schema columns, classify public/private",
            scripts=[
                {"script": "processing/combine_grundschulen_and_metadata.py", "args": ""},
            ],
            input_files=[
                "data_berlin_primary/raw/bildung_berlin_grundschulen.csv",
            ],
            output_files=[
                "data_berlin_primary/intermediate/combined_grundschulen_with_metadata.csv",
            ],
            estimated_duration=2,
        ),

        # Phase 3: Traffic Enrichment (includes geocoding)
        PipelinePhase(
            id=3,
            name="Traffic Data Enrichment",
            description="Geocode schools and add traffic sensor data from Berlin",
            scripts=[
                {"script": "enrichment/enrich_grundschulen_with_traffic.py", "args": ""},
            ],
            input_files=[
                "data_berlin_primary/intermediate/combined_grundschulen_with_metadata.csv",
            ],
            output_files=[
                "data_berlin_primary/intermediate/combined_grundschulen_with_metadata.csv",  # Updated in place
            ],
            estimated_duration=15,  # Geocoding + traffic matching
        ),

        # Phase 4: Crime Data Enrichment
        PipelinePhase(
            id=4,
            name="Crime Data Enrichment",
            description="Add Berlin district crime statistics from local data asset",
            scripts=[
                {"script": "../scripts_shared/enrichment/enrich_berlin_schools_with_crime.py",
                 "args": "--input data_berlin_primary/intermediate/combined_grundschulen_with_metadata.csv"},
            ],
            input_files=[
                "data_berlin_primary/intermediate/combined_grundschulen_with_metadata.csv",
                "data_berlin/raw/bezirk_crime_statistics.csv",
            ],
            output_files=[
                "data_berlin_primary/intermediate/combined_grundschulen_with_metadata.csv",  # Updated in place
            ],
            estimated_duration=1,  # Quick local merge
        ),

        # Phase 5: School Statistics Enrichment
        PipelinePhase(
            id=5,
            name="School Statistics Enrichment",
            description="Add student/teacher counts from bildungsstatistik.berlin.de",
            scripts=[
                {"script": "../scripts_berlin/scrapers/download_bildungsstatistik_csv.py", "args": ""},
                {"script": "../scripts_shared/enrichment/enrich_berlin_schools_with_statistics.py",
                 "args": "--input data_berlin_primary/intermediate/combined_grundschulen_with_metadata.csv"},
            ],
            input_files=[
                "data_berlin_primary/intermediate/combined_grundschulen_with_metadata.csv",
            ],
            output_files=[
                "data_berlin/raw/bildungsstatistik_2024_25.csv",
                "data_berlin/raw/bildungsstatistik_2023_24.csv",
                "data_berlin_primary/intermediate/combined_grundschulen_with_metadata.csv",  # Updated in place
            ],
            estimated_duration=2,  # Download + merge
        ),

        # Phase 6: Transit Enrichment
        PipelinePhase(
            id=6,
            name="Public Transit Enrichment",
            description="Add BVG public transit accessibility data (U/S-Bahn, Tram, Bus)",
            scripts=[
                {"script": "enrichment/enrich_grundschulen_with_transit.py", "args": ""},
            ],
            input_files=[
                "data_berlin_primary/intermediate/combined_grundschulen_with_metadata.csv",
            ],
            output_files=[
                "data_berlin_primary/intermediate/combined_grundschulen_with_metadata.csv",  # Updated in place
            ],
            estimated_duration=30,  # ~400 schools * 0.7s delay per school
        ),

        # Phase 7: POI Enrichment
        PipelinePhase(
            id=7,
            name="Points of Interest Enrichment",
            description="Add nearby POIs (supermarkets, kitas, parks, etc.) using Google Places API",
            scripts=[
                {"script": "enrichment/enrich_grundschulen_with_pois.py", "args": ""},
            ],
            input_files=[
                "data_berlin_primary/intermediate/combined_grundschulen_with_metadata.csv",
            ],
            output_files=[
                "data_berlin_primary/intermediate/combined_grundschulen_with_metadata.csv",  # Updated in place
            ],
            estimated_duration=20,  # Parallel processing, ~5 workers
        ),

        # Phase 8: School Descriptions Generation
        PipelinePhase(
            id=8,
            name="School Descriptions Generation",
            description="Crawl school websites and generate rich descriptions using LLM",
            scripts=[
                {"script": "../scripts_shared/generation/generate_school_descriptions_v4.py",
                 "args": "--input data_berlin_primary/intermediate/combined_grundschulen_with_metadata.csv --output data_berlin_primary/final/grundschule_master_table_final.csv"},
            ],
            input_files=[
                "data_berlin_primary/intermediate/combined_grundschulen_with_metadata.csv",
            ],
            output_files=[
                "data_berlin_primary/final/grundschule_master_table_final.csv",
                "data_berlin_primary/descriptions/",
            ],
            estimated_duration=180,  # This is the longest phase
        ),

        # Phase 9: Website Metadata Extraction
        PipelinePhase(
            id=9,
            name="Website Metadata Extraction",
            description="Extract sprachen, gruendungsjahr, besonderheiten from school websites using LLM",
            scripts=[
                {"script": "../scripts_shared/enrichment/enrich_berlin_schools_with_website_metadata.py",
                 "args": "--input data_berlin_primary/final/grundschule_master_table_final.csv"},
            ],
            input_files=[
                "data_berlin_primary/final/grundschule_master_table_final.csv",
            ],
            output_files=[
                "data_berlin_primary/final/grundschule_master_table_final.csv",  # Updated in place
            ],
            estimated_duration=15,  # ~500 schools * ~1.5s per school
        ),

        # Phase 10: Embeddings & Similarity (Optional)
        PipelinePhase(
            id=10,
            name="Embeddings & Similarity Computation",
            description="Generate OpenAI embeddings and compute school similarity scores",
            scripts=[],  # Custom function handles this
            input_files=[
                "data_berlin_primary/final/grundschule_master_table_final.csv",
            ],
            output_files=[
                "data_berlin_primary/final/grundschule_master_table_final_with_embeddings.parquet",
            ],
            estimated_duration=10,
            custom_function=None,  # Will be set below
        ),
    ]

    return phases


class PipelineOrchestrator:
    """
    Orchestrates the execution of the Berlin primary school data pipeline.

    This class manages the sequential execution of pipeline phases,
    handles dependencies, provides progress tracking, and manages
    error recovery.

    Attributes:
        base_dir: Base directory containing all scripts and data
        phases: List of pipeline phases to execute
        console: Rich console for output (if available)
        dry_run: If True, only show what would be executed
    """

    def __init__(self, base_dir: Optional[Path] = None, dry_run: bool = False):
        """
        Initialize the pipeline orchestrator.

        Args:
            base_dir: Base directory for scripts and data. Defaults to project root.
            dry_run: If True, don't actually execute anything.
        """
        # Base dir is project root (parent of scripts_berlin_primary)
        self.base_dir = base_dir or Path(__file__).parent.parent
        self.scripts_dir = self.base_dir / "scripts_berlin_primary"
        self.dry_run = dry_run
        self.phases = define_pipeline_phases()
        self.start_time = None
        self.console = Console() if RICH_AVAILABLE else None

        # Set custom function for Phase 10 (Embeddings)
        for phase in self.phases:
            if phase.id == 10:
                phase.custom_function = self._run_embeddings_phase

    def _print(self, message: str, style: str = None):
        """Print message using Rich if available, otherwise plain print."""
        if self.console and RICH_AVAILABLE:
            self.console.print(message, style=style)
        else:
            print(message)

    def _check_file_exists(self, filename: str) -> bool:
        """Check if a file exists in the base directory."""
        filepath = self.base_dir / filename
        return filepath.exists()

    def _check_dependencies(self, phase: PipelinePhase) -> Tuple[bool, List[str]]:
        """
        Check if all input dependencies for a phase exist.

        Args:
            phase: The phase to check dependencies for.

        Returns:
            Tuple of (all_satisfied, list_of_missing_files)
        """
        missing = []
        for input_file in phase.input_files:
            if not self._check_file_exists(input_file):
                missing.append(input_file)

        return len(missing) == 0, missing

    def _run_script(self, script_info: Dict[str, str], phase_name: str) -> Tuple[bool, str]:
        """
        Execute a single Python script.

        Args:
            script_info: Dictionary with 'script' and 'args' keys
            phase_name: Name of the current phase (for logging)

        Returns:
            Tuple of (success, output_or_error_message)
        """
        script = script_info["script"]
        args = script_info.get("args", "")

        # Handle relative paths - scripts starting with ../ are relative to scripts_berlin_primary
        if script.startswith("../"):
            script_path = self.scripts_dir / script
        else:
            script_path = self.scripts_dir / script

        script_path = script_path.resolve()
        if not script_path.exists():
            return False, f"Script not found: {script_path}"

        cmd = f"python3 {script_path}"
        if args:
            cmd += f" {args}"

        logger.info(f"[{phase_name}] Running: {cmd}")

        if self.dry_run:
            return True, f"[DRY RUN] Would execute: {cmd}"

        try:
            # Run the script and capture output in real-time
            process = subprocess.Popen(
                cmd,
                shell=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                cwd=self.base_dir,
            )

            output_lines = []
            while True:
                line = process.stdout.readline()
                if not line and process.poll() is not None:
                    break
                if line:
                    line = line.rstrip()
                    output_lines.append(line)
                    # Show progress lines
                    if any(kw in line.lower() for kw in ['processing', 'progress', 'completed', '%', 'updated', 'saved', 'loaded']):
                        logger.info(f"  {line}")

            return_code = process.wait()
            output = "\n".join(output_lines)

            if return_code == 0:
                return True, output
            else:
                return False, f"Script failed with code {return_code}:\n{output}"

        except Exception as e:
            return False, f"Error running script: {str(e)}"

    def _run_embeddings_phase(self) -> Tuple[bool, str]:
        """
        Custom function for Phase 7: Generate embeddings and compute similarity.

        This phase:
        1. Loads the enriched CSV
        2. Generates metadata descriptions for schools missing them
        3. Generates embeddings using OpenAI text-embedding-3-large
        4. Computes cosine similarity between all schools
        5. Adds top 3 most similar schools for each school
        6. Saves to parquet format

        Returns:
            Tuple of (success, message)
        """
        if self.dry_run:
            return True, "[DRY RUN] Would generate embeddings and compute similarity"

        try:
            import yaml
            import numpy as np
            import pandas as pd
            import requests
            from sklearn.metrics.pairwise import cosine_similarity

            # Load config
            config_path = self.base_dir / "config.yaml"
            with open(config_path, 'r') as f:
                config = yaml.safe_load(f)

            api_key = config.get('api_keys', {}).get('openai')
            if not api_key:
                return False, "OpenAI API key not found in config.yaml"

            # Load data
            logger.info("Loading data...")
            input_file = self.base_dir / "data_berlin_primary/final/grundschule_master_table_final.csv"
            if not input_file.exists():
                input_file = self.base_dir / "data_berlin_primary/intermediate/combined_grundschulen_with_metadata.csv"

            df = pd.read_csv(input_file)
            logger.info(f"  Loaded {len(df)} schools")

            # Generate descriptions for schools missing them
            def generate_description_from_metadata(row):
                parts = []
                name = row.get('schulname', '')
                school_type = row.get('school_type', 'Grundschule')
                traegerschaft = row.get('traegerschaft', '')

                if name:
                    ownership = f" ({traegerschaft})" if pd.notna(traegerschaft) else ""
                    parts.append(f"{name} is a {school_type}{ownership} in Berlin.")

                bezirk = row.get('bezirk', '')
                ortsteil = row.get('ortsteil', '')
                plz = row.get('plz', '')

                location_parts = []
                if pd.notna(ortsteil) and ortsteil:
                    location_parts.append(str(ortsteil))
                if pd.notna(bezirk) and bezirk:
                    location_parts.append(f"district of {bezirk}")
                if pd.notna(plz) and plz:
                    location_parts.append(f"postal code {int(plz) if isinstance(plz, float) else plz}")

                if location_parts:
                    parts.append(f"Located in {', '.join(location_parts)}.")

                schueler = row.get('schueler_2024_25')
                lehrer = row.get('lehrer_2024_25')

                if pd.notna(schueler) and schueler > 0:
                    student_str = f"The school has approximately {int(schueler)} students"
                    if pd.notna(lehrer) and lehrer > 0:
                        ratio = schueler / lehrer
                        student_str += f" and {int(lehrer)} teachers (student-teacher ratio: {ratio:.1f}:1)"
                    student_str += "."
                    parts.append(student_str)

                # Transit accessibility
                score = row.get('transit_accessibility_score')
                if pd.notna(score):
                    parts.append(f"Transit accessibility score: {int(score)}/100.")

                return " ".join(parts)

            # Check if description column exists
            if 'description' not in df.columns:
                df['description'] = None

            # Fill missing descriptions
            missing_mask = df['description'].isna() | (df['description'].apply(lambda x: len(str(x)) if pd.notna(x) else 0) < 100)
            missing_count = missing_mask.sum()

            if missing_count > 0:
                logger.info(f"  Generating descriptions for {missing_count} schools...")
                for idx in df[missing_mask].index:
                    df.at[idx, 'description'] = generate_description_from_metadata(df.loc[idx])

            # Generate embeddings
            logger.info("Generating embeddings with text-embedding-3-large...")

            MODEL = "text-embedding-3-large"
            BASE_URL = "https://api.openai.com/v1/embeddings"

            headers = {
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json"
            }

            descriptions = df['description'].tolist()
            all_embeddings = []
            batch_size = 10

            for i in range(0, len(descriptions), batch_size):
                batch = descriptions[i:i + batch_size]
                batch = [str(t)[:15000] if t else "No description" for t in batch]

                data = {"model": MODEL, "input": batch}
                response = requests.post(BASE_URL, headers=headers, json=data, timeout=120)
                response.raise_for_status()

                result = response.json()
                batch_embeddings = [item["embedding"] for item in result["data"]]
                all_embeddings.extend(batch_embeddings)

                logger.info(f"  Embeddings: {i + len(batch)}/{len(descriptions)}")
                time.sleep(0.3)

            embeddings_array = np.array(all_embeddings)
            logger.info(f"  Embedding shape: {embeddings_array.shape}")

            # Add embeddings to dataframe
            df['embedding'] = list(embeddings_array)

            # Compute similarity
            logger.info("Computing cosine similarity...")
            similarity_matrix = cosine_similarity(embeddings_array)

            # Find top 3 most similar for each school
            logger.info("Finding top 3 most similar schools...")
            schulnummers = df['schulnummer'].tolist()

            most_similar_01 = []
            most_similar_02 = []
            most_similar_03 = []

            for i in range(len(df)):
                similarities = similarity_matrix[i].copy()
                similarities[i] = -1
                top_indices = np.argsort(similarities)[::-1][:3]

                most_similar_01.append(schulnummers[top_indices[0]])
                most_similar_02.append(schulnummers[top_indices[1]])
                most_similar_03.append(schulnummers[top_indices[2]])

            df['most_similar_school_no_01'] = most_similar_01
            df['most_similar_school_no_02'] = most_similar_02
            df['most_similar_school_no_03'] = most_similar_03

            # Ensure output directory exists
            output_dir = self.base_dir / "data_berlin_primary/final"
            output_dir.mkdir(parents=True, exist_ok=True)

            # Save to parquet
            output_path = output_dir / "grundschule_master_table_final_with_embeddings.parquet"
            logger.info(f"Saving to {output_path}...")
            df.to_parquet(output_path, index=False)

            return True, f"Successfully generated embeddings and saved to {output_path}"

        except Exception as e:
            import traceback
            return False, f"Error in embeddings phase: {str(e)}\n{traceback.format_exc()}"

    def run_phase(self, phase: PipelinePhase) -> bool:
        """
        Execute a single pipeline phase.

        Args:
            phase: The phase to execute.

        Returns:
            True if phase completed successfully, False otherwise.
        """
        phase.status = PhaseStatus.RUNNING

        self._print(f"\n{'='*60}", style="bold blue")
        self._print(f"Phase {phase.id}: {phase.name}", style="bold blue")
        self._print(f"{'='*60}", style="bold blue")
        self._print(f"\n{phase.description}\n")

        # Check dependencies
        deps_satisfied, missing = self._check_dependencies(phase)
        if not deps_satisfied:
            self._print(f"Missing dependencies: {missing}", style="bold red")
            self._print("Attempting to continue anyway...", style="yellow")

        # Run custom function if defined
        if phase.custom_function:
            self._print("Running custom phase logic...", style="cyan")
            success, message = phase.custom_function()
            if success:
                phase.status = PhaseStatus.COMPLETED
                self._print(f"Phase {phase.id} completed successfully!", style="bold green")
            else:
                phase.status = PhaseStatus.FAILED
                self._print(f"Phase {phase.id} failed: {message}", style="bold red")
            return success

        # Run scripts
        for script_info in phase.scripts:
            script_name = script_info["script"]
            self._print(f"\nRunning: {script_name}", style="cyan")

            success, output = self._run_script(script_info, phase.name)

            if not success:
                phase.status = PhaseStatus.FAILED
                self._print(f"Failed: {output}", style="bold red")
                return False

            self._print(f"Completed: {script_name}", style="green")

        # Verify outputs
        for output_file in phase.output_files:
            if not self._check_file_exists(output_file):
                self._print(f"Warning: Expected output not found: {output_file}", style="yellow")

        phase.status = PhaseStatus.COMPLETED
        self._print(f"\nPhase {phase.id} completed successfully!", style="bold green")
        return True

    def run_pipeline(
        self,
        phases_to_run: Optional[List[int]] = None,
        skip_phases: Optional[List[int]] = None,
        start_from: Optional[int] = None,
    ) -> bool:
        """
        Execute the complete pipeline or specified phases.

        Args:
            phases_to_run: Specific phase IDs to run. If None, runs all.
            skip_phases: Phase IDs to skip.
            start_from: Start from this phase ID (skip earlier phases).

        Returns:
            True if all phases completed successfully.
        """
        self.start_time = datetime.now()

        # Determine which phases to run
        phases = self.phases.copy()

        if phases_to_run:
            phases = [p for p in phases if p.id in phases_to_run]

        if skip_phases:
            phases = [p for p in phases if p.id not in skip_phases]

        if start_from:
            phases = [p for p in phases if p.id >= start_from]

        # Print pipeline summary
        self._print_pipeline_summary(phases)

        # Run phases
        total_phases = len(phases)
        completed_phases = 0

        if RICH_AVAILABLE and self.console:
            with Progress(
                SpinnerColumn(),
                TextColumn("[bold blue]{task.description}"),
                BarColumn(),
                TaskProgressColumn(),
                TimeElapsedColumn(),
                console=self.console,
            ) as progress:
                overall_task = progress.add_task(
                    f"[bold]Pipeline Progress",
                    total=total_phases,
                )

                for phase in phases:
                    progress.update(
                        overall_task,
                        description=f"[bold]Phase {phase.id}: {phase.name}",
                    )

                    success = self.run_phase(phase)

                    if success:
                        completed_phases += 1
                        progress.advance(overall_task)
                    else:
                        self._print(f"\nPipeline stopped at Phase {phase.id}", style="bold red")
                        break
        else:
            for i, phase in enumerate(phases):
                print(f"\n[Pipeline Progress: {i+1}/{total_phases}]")

                success = self.run_phase(phase)

                if success:
                    completed_phases += 1
                else:
                    print(f"\nPipeline stopped at Phase {phase.id}")
                    break

        # Print summary
        self._print_final_summary(completed_phases, total_phases)

        return completed_phases == total_phases

    def _print_pipeline_summary(self, phases: List[PipelinePhase]):
        """Print a summary of phases to be executed."""
        self._print("\n" + "="*70, style="bold")
        self._print("BERLIN PRIMARY SCHOOL (GRUNDSCHULE) DATA ASSET BUILDER", style="bold cyan")
        self._print("="*70, style="bold")

        if RICH_AVAILABLE:
            table = Table(title="Pipeline Phases")
            table.add_column("Phase", style="cyan")
            table.add_column("Name", style="white")
            table.add_column("Est. Duration", style="yellow")
            table.add_column("Scripts", style="green")

            for phase in phases:
                scripts = ", ".join([s["script"] for s in phase.scripts]) or "Custom"
                table.add_row(
                    str(phase.id),
                    phase.name,
                    f"{phase.estimated_duration} min",
                    scripts[:40] + "..." if len(scripts) > 40 else scripts,
                )

            self.console.print(table)
        else:
            print("\nPhases to execute:")
            for phase in phases:
                print(f"  {phase.id}. {phase.name} (~{phase.estimated_duration} min)")

        total_time = sum(p.estimated_duration for p in phases)
        self._print(f"\nEstimated total duration: {total_time} minutes ({total_time/60:.1f} hours)", style="yellow")
        self._print("")

    def _print_final_summary(self, completed: int, total: int):
        """Print final pipeline summary."""
        elapsed = datetime.now() - self.start_time

        self._print("\n" + "="*70, style="bold")
        self._print("PIPELINE COMPLETE", style="bold green" if completed == total else "bold red")
        self._print("="*70, style="bold")

        self._print(f"\nPhases completed: {completed}/{total}")
        self._print(f"Total time: {elapsed}")

        if completed == total:
            self._print("\nFinal output: data_berlin_primary/final/grundschule_master_table_final.csv", style="bold green")

        # Show phase statuses
        if RICH_AVAILABLE:
            table = Table(title="Phase Status")
            table.add_column("Phase", style="cyan")
            table.add_column("Name", style="white")
            table.add_column("Status", style="white")

            for phase in self.phases:
                status_style = {
                    PhaseStatus.COMPLETED: "green",
                    PhaseStatus.FAILED: "red",
                    PhaseStatus.SKIPPED: "yellow",
                    PhaseStatus.PENDING: "dim",
                    PhaseStatus.RUNNING: "blue",
                }.get(phase.status, "white")

                table.add_row(
                    str(phase.id),
                    phase.name,
                    f"[{status_style}]{phase.status.value}[/{status_style}]",
                )

            self.console.print(table)


def main():
    """Main entry point for the orchestrator."""
    parser = argparse.ArgumentParser(
        description="Berlin Primary School (Grundschule) Data Asset Builder Orchestrator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Run complete pipeline
  python3 Berlin_primary_school_data_asset_builder_orchestrator.py

  # Run specific phases only
  python3 Berlin_primary_school_data_asset_builder_orchestrator.py --phases 1,2,3

  # Skip certain phases
  python3 Berlin_primary_school_data_asset_builder_orchestrator.py --skip-phases 6,7

  # Resume from phase 3
  python3 Berlin_primary_school_data_asset_builder_orchestrator.py --start-from 3

  # Dry run (show what would be executed)
  python3 Berlin_primary_school_data_asset_builder_orchestrator.py --dry-run
        """
    )

    parser.add_argument(
        "--phases",
        type=str,
        help="Comma-separated list of phase IDs to run (e.g., '1,2,3')",
    )
    parser.add_argument(
        "--skip-phases",
        type=str,
        help="Comma-separated list of phase IDs to skip (e.g., '6,7')",
    )
    parser.add_argument(
        "--start-from",
        type=int,
        help="Start from this phase ID (skip earlier phases)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be executed without actually running",
    )
    parser.add_argument(
        "--base-dir",
        type=str,
        help="Base directory for scripts and data",
    )

    args = parser.parse_args()

    # Parse phase lists
    phases_to_run = None
    if args.phases:
        phases_to_run = [int(p.strip()) for p in args.phases.split(",")]

    skip_phases = None
    if args.skip_phases:
        skip_phases = [int(p.strip()) for p in args.skip_phases.split(",")]

    # Create and run orchestrator
    base_dir = Path(args.base_dir) if args.base_dir else None
    orchestrator = PipelineOrchestrator(base_dir=base_dir, dry_run=args.dry_run)

    success = orchestrator.run_pipeline(
        phases_to_run=phases_to_run,
        skip_phases=skip_phases,
        start_from=args.start_from,
    )

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
